# Generated by Django 5.1.6 on 2025-05-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='estimated_cost',
        ),
        migrations.AddField(
            model_name='appointment',
            name='shared_records',
            field=models.ManyToManyField(blank=True, to='core.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
