# Generated by Django 5.1.6 on 2025-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_appointment_estimated_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimated_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(),
        ),
    ]
