# Generated by Django 5.1.6 on 2025-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_estimated_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimate_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
